name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -U pip setuptools
        go install github.com/bazelbuild/bazelisk@latest
        

    - name: Build project
      run: |
        git submodule update --init --recursive
        python script/apply_patch.py
        # bash script/build_plugin.sh -a
        cmake -S . -B build -DENABLE_BUILD_PLUGIN=ON
        cmake --build build
        pip wheel .

    - name: Run tests
      run: |
        ls | grep whl | xargs -I {} pip install --force-reinstall {}
        python test/python/test_init.py
        python test/model/mnist.py
        cd build
        ctest -R

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/Testing/Temporary
